import type { Metadata } from "next";

import "./globals.css";
import Header from '@/components/Header'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ fontSize: '10px', lineHeight: '1.15' }}>
      <head>
        <link rel="preload" href="https://use.typekit.net/iqh1stq.css" as="style" />
        <link rel="stylesheet" href="https://use.typekit.net/iqh1stq.css" />
      </head>
      <body className="bg-blue text-[1.6rem]">
        <Header />
        {children}
      </body>
    </html>
  );
}